name: Rest Api CI

on:
  push:
    branches: [ master , development]
  pull_request:
    branches: [ master , development]

jobs:
  build:
    environment: restapitellierc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
        envkey_MONGODB_PROD_URI: ${{ secrets.MONGODB_PROD_URI }}
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test